development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: <%= ENV['PRIVATE_PUB_URL'] %>
  secret_token: <%= ENV['PRIVATE_PUB_SECRET_KEY'] %>
  signature_expiration: 3600 # one hour
